// ──────────────────────────────────────────────
// Pravi — Central Constants & Enums
// Single source of truth for all domain enums.
// Both backend logic and frontend dropdowns
// should derive from these values.
// ──────────────────────────────────────────────

// ── User Roles ──────────────────────────────
const ROLES = {
  ADMIN: 'ADMIN',
  ASSET_MANAGER: 'ASSET_MANAGER',
  TECHNICIAN: 'TECHNICIAN',
  EMPLOYEE: 'EMPLOYEE',
};

const ROLE_LIST = Object.values(ROLES);

// ── Physical Asset Categories ───────────────
const ASSET_CATEGORIES = {
  HEAVY_MACHINERY: 'HEAVY_MACHINERY',
  HVAC_AND_FACILITIES: 'HVAC_AND_FACILITIES',
  ELECTRICAL_EQUIPMENT: 'ELECTRICAL_EQUIPMENT',
  FLEET_VEHICLE: 'FLEET_VEHICLE',
  WAREHOUSE_EQUIPMENT: 'WAREHOUSE_EQUIPMENT',
  TOOLS_AND_APPARATUS: 'TOOLS_AND_APPARATUS',
  OFFICE_INFRASTRUCTURE: 'OFFICE_INFRASTRUCTURE',
};

const ASSET_CATEGORY_LIST = Object.values(ASSET_CATEGORIES);

// Short prefix used for auto-generated asset tags
// e.g., HEAVY_MACHINERY → HM, so tag becomes AST-HM-2026-0001
const ASSET_CATEGORY_PREFIX = {
  HEAVY_MACHINERY: 'HM',
  HVAC_AND_FACILITIES: 'HV',
  ELECTRICAL_EQUIPMENT: 'EL',
  FLEET_VEHICLE: 'FV',
  WAREHOUSE_EQUIPMENT: 'WH',
  TOOLS_AND_APPARATUS: 'TA',
  OFFICE_INFRASTRUCTURE: 'OI',
};

// ── Physical Condition Rating ───────────────
const PHYSICAL_CONDITIONS = {
  BRAND_NEW: 'BRAND_NEW',
  GOOD: 'GOOD',
  FAIR: 'FAIR',
  NEEDS_REPAIR: 'NEEDS_REPAIR',
  DAMAGED: 'DAMAGED',
  CONDEMNED: 'CONDEMNED',
};

const PHYSICAL_CONDITION_LIST = Object.values(PHYSICAL_CONDITIONS);

// ── Asset Lifecycle Statuses ────────────────
const ASSET_STATUS = {
  PROCURED: 'PROCURED',
  RECEIVED: 'RECEIVED',
  IN_STOCK: 'IN_STOCK',
  ASSIGNED: 'ASSIGNED',
  IN_USE: 'IN_USE',
  UNDER_MAINTENANCE: 'UNDER_MAINTENANCE',
  IN_TRANSIT: 'IN_TRANSIT',
  CONDEMNED: 'CONDEMNED',
  DISPOSED: 'DISPOSED',
};

const ASSET_STATUS_LIST = Object.values(ASSET_STATUS);

// Allowed state transitions — the lifecycle state machine.
// Key = current status, Value = array of statuses it can move to.
const ASSET_STATUS_TRANSITIONS = {
  PROCURED: ['RECEIVED'],
  RECEIVED: ['IN_STOCK'],
  IN_STOCK: ['ASSIGNED', 'IN_USE'],
  ASSIGNED: ['IN_USE', 'IN_STOCK'],
  IN_USE: ['UNDER_MAINTENANCE', 'IN_TRANSIT', 'CONDEMNED'],
  UNDER_MAINTENANCE: ['IN_USE', 'CONDEMNED'],
  IN_TRANSIT: ['IN_USE'], // Destination site confirms delivery
  CONDEMNED: ['DISPOSED'],
  DISPOSED: [], // Terminal state — no transitions allowed
};

// ── Transfer / Gate Pass Statuses ───────────
const TRANSFER_STATUS = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  DISPATCHED: 'DISPATCHED',
  DELIVERED: 'DELIVERED',
  REJECTED: 'REJECTED',
};

const TRANSFER_STATUS_LIST = Object.values(TRANSFER_STATUS);

const GATE_PASS_TYPES = {
  RETURNABLE: 'RETURNABLE',
  NON_RETURNABLE: 'NON_RETURNABLE',
};

const GATE_PASS_TYPE_LIST = Object.values(GATE_PASS_TYPES);

// ── Maintenance ─────────────────────────────
const MAINTENANCE_TYPES = {
  PREVENTIVE_SCHEDULED: 'PREVENTIVE_SCHEDULED',
  BREAKDOWN_REPAIR: 'BREAKDOWN_REPAIR',
  INSPECTION: 'INSPECTION',
  CALIBRATION: 'CALIBRATION',
};

const MAINTENANCE_TYPE_LIST = Object.values(MAINTENANCE_TYPES);

const MAINTENANCE_PRIORITY = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
};

const MAINTENANCE_PRIORITY_LIST = Object.values(MAINTENANCE_PRIORITY);

const MAINTENANCE_STATUS = {
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_PARTS: 'WAITING_FOR_PARTS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

const MAINTENANCE_STATUS_LIST = Object.values(MAINTENANCE_STATUS);

// ── Asset Event Types ───────────────────────
const EVENT_TYPES = {
  CREATED: 'CREATED',
  TAG_AFFIXED: 'TAG_AFFIXED',
  RECEIVED: 'RECEIVED',
  STOCKED: 'STOCKED',
  INSTALLED: 'INSTALLED',
  ASSIGNED: 'ASSIGNED',
  UNASSIGNED: 'UNASSIGNED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  CONDITION_UPDATED: 'CONDITION_UPDATED',
  TRANSFER_REQUESTED: 'TRANSFER_REQUESTED',
  TRANSFER_DISPATCHED: 'TRANSFER_DISPATCHED',
  TRANSFER_DELIVERED: 'TRANSFER_DELIVERED',
  MAINTENANCE_OPENED: 'MAINTENANCE_OPENED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  CONDEMNED: 'CONDEMNED',
  DISPOSED: 'DISPOSED',
};

const EVENT_TYPE_LIST = Object.values(EVENT_TYPES);

module.exports = {
  ROLES,
  ROLE_LIST,
  ASSET_CATEGORIES,
  ASSET_CATEGORY_LIST,
  ASSET_CATEGORY_PREFIX,
  PHYSICAL_CONDITIONS,
  PHYSICAL_CONDITION_LIST,
  ASSET_STATUS,
  ASSET_STATUS_LIST,
  ASSET_STATUS_TRANSITIONS,
  TRANSFER_STATUS,
  TRANSFER_STATUS_LIST,
  GATE_PASS_TYPES,
  GATE_PASS_TYPE_LIST,
  MAINTENANCE_TYPES,
  MAINTENANCE_TYPE_LIST,
  MAINTENANCE_PRIORITY,
  MAINTENANCE_PRIORITY_LIST,
  MAINTENANCE_STATUS,
  MAINTENANCE_STATUS_LIST,
  EVENT_TYPES,
  EVENT_TYPE_LIST,
};
